# Generated by Django 3.0.5 on 2020-10-02 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gis_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=-1.0)),
                ('lon', models.FloatField(default=-1.0)),
                ('schedule', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AtmBusStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0)),
                ('id_atm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ATM')),
            ],
        ),
        migrations.CreateModel(
            name='AtmParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ATM')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gis_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gis_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='authorjournal',
            name='id_auth',
        ),
        migrations.RemoveField(
            model_name='authorjournal',
            name='id_journal',
        ),
        migrations.RemoveField(
            model_name='authorsubject',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='authorsubject',
            name='id_sub',
        ),
        migrations.RemoveField(
            model_name='authoruniversity',
            name='id_auth',
        ),
        migrations.RemoveField(
            model_name='authoruniversity',
            name='id_university',
        ),
        migrations.RemoveField(
            model_name='document',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='issn',
        ),
        migrations.RemoveField(
            model_name='documentauthoruniversity',
            name='id_auth',
        ),
        migrations.RemoveField(
            model_name='documentauthoruniversity',
            name='id_doc',
        ),
        migrations.RemoveField(
            model_name='documentauthoruniversity',
            name='id_university',
        ),
        migrations.RemoveField(
            model_name='documentsubject',
            name='id_doc',
        ),
        migrations.RemoveField(
            model_name='documentsubject',
            name='id_sub',
        ),
        migrations.RemoveField(
            model_name='university',
            name='state',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorJournal',
        ),
        migrations.DeleteModel(
            name='AuthorSubject',
        ),
        migrations.DeleteModel(
            name='AuthorUniversity',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentAuthorUniversity',
        ),
        migrations.DeleteModel(
            name='DocumentSubject',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.AddField(
            model_name='atmparking',
            name='id_parking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Parking'),
        ),
        migrations.AddField(
            model_name='atmbusstations',
            name='id_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.BusStation'),
        ),
        migrations.AddField(
            model_name='atm',
            name='bank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Bank'),
        ),
    ]
