# Generated by Django 3.0.5 on 2020-10-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201002_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmCrowdedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0)),
                ('id_atm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ATM')),
            ],
        ),
        migrations.CreateModel(
            name='CrowdedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('gis_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gis_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=-1.0)),
                ('lon', models.FloatField(default=-1.0)),
                ('geometries', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='atmparking',
            name='id_atm',
        ),
        migrations.RemoveField(
            model_name='atmparking',
            name='id_parking',
        ),
        migrations.DeleteModel(
            name='AtmBusStations',
        ),
        migrations.DeleteModel(
            name='AtmParking',
        ),
        migrations.DeleteModel(
            name='BusStation',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.AddField(
            model_name='atmcrowdedplace',
            name='id_place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.CrowdedPlace'),
        ),
    ]
