# Generated by Django 3.0.5 on 2020-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201003_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='geometries',
        ),
        migrations.AddField(
            model_name='district',
            name='geometry',
            field=models.TextField(default=''),
        ),
    ]
