# Generated by Django 3.0.5 on 2020-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201003_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
