# Generated by Django 3.0.5 on 2020-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_district_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdedplace',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crowdedplace',
            name='lat',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='crowdedplace',
            name='lon',
            field=models.FloatField(default=-1.0),
        ),
    ]
