# Generated by Django 3.0.5 on 2020-10-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201003_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmcrowdedplace',
            name='measure',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
