# Generated by Django 3.0.5 on 2020-10-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_atmcrowdedplace_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcrowdedplace',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
