# Generated by Django 3.0.5 on 2020-10-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_atmcrowdedplace_multi_line_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_id', models.CharField(max_length=200)),
                ('wkt_geo', models.TextField(default='')),
                ('district', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.District')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(default=-1)),
                ('age_min', models.IntegerField(default=-1)),
                ('age_max', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('abnt_cnt', models.FloatField(default=0.0)),
                ('square_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Polygons')),
            ],
        ),
    ]
