# Generated by Django 3.0.5 on 2020-10-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_peopleflow_polygons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_id', models.CharField(max_length=200)),
                ('wkt_geo', models.TextField(default='')),
                ('district', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.District')),
            ],
        ),
        migrations.AlterField(
            model_name='peopleflow',
            name='square_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Polygon'),
        ),
        migrations.DeleteModel(
            name='Polygons',
        ),
    ]
