# Generated by Django 3.0.5 on 2020-10-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201003_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdedplace',
            name='square_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Polygon'),
        ),
    ]
